apiVersion: v1
kind: Pod
metadata:
  name: private-image-test-1
spec:
  containers:
    - name: uses-private-image
      image: alpine:edge
      imagePullPolicy: IfNotPresent
      command: [ "echo", "SUCCESS" ]